POST https://node-do-zero-ao-crud.onrender.com/videos
Content-Type: application/json

{
    "title":"Video teste",
    "description":"esse é meu primeiro video teste",
    "duration":180
}

###

GET https://node-do-zero-ao-crud.onrender.com/videos

###
PUT https://node-do-zero-ao-crud.onrender.com/videos/bc94b29f-6319-4937-8e2b-14196eddd146
Content-Type: application/json

{
    "title":"video teste node",
    "description":"deuvsvss",
    "duration":12380
}

###
DELETE https://node-do-zero-ao-crud.onrender.com/videos/bc94b29f-6319-4937-8e2b-14196eddd146

