POST http://localhost:3333/videos
Content-Type: application/json

{
    "title":"video node",
    "description":"esse é meu primeiro video",
    "duration":180
}

###

GET http://localhost:3333/videos?search=node

###
PUT http://localhost:3333/videos/a3d18d1a-b966-47af-8682-05562b79d8ab
Content-Type: application/json

{
    "title":"video 04",
    "description":"deus",
    "duration":180
}

###
DELETE http://localhost:3333/videos/a3d18d1a-b966-47af-8682-05562b79d8ab

